// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sctmovllywhwglndawqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjdG1vdmxseXdod2dsbmRhd3FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTg5NzcsImV4cCI6MjA2MTA3NDk3N30.ZEiwZfhOpU3iPcZIuJ9b5SSKmXvKoFfQIlcBfZjYIYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);